### ISSUE TITLE
🐛[BUG] Watchlist no longer works with Home Screen Sections plugin

### ISSUE THREAD

**Issue by kazango** [n00bcodr/Jellyfin-Enhanced#126]
**Describe the bug**

Before this update and after updating Jellyfin the home section for watchlist showed. After updating the plugin it no longer shows in the home sections.

I’ll also mention clicking the watchlist tab I made with the tabs plugin is hit and miss whether anything shows since updating this plugin. It used to load fine, and the previous update allowed horizontal scrolling on mobile and fixed that bug. Also tried private tabs and clearing cache, when I refresh the page the container sometimes seems to restart or crash.

**Expected behavior**

The watchlist should show as a section in the jellyfin home sections plugin. The watchlist should also load every time when clicking the watchlist tab.

**Screenshots**

Currently on mobile but I updated this plugin this morning and have experienced these issues since updating where the watchlist tab is blank and there is no longer a watchlist section in the Home Screen. Can probably provide screenshots if necessary.

**Jellyfin Environment (please complete the following information):**
 - Server Version: [e.g. 10.9.9, 10.10.7]
 - 10.11.0
 - Plugin Version: [e.g. 5.1.0.0, 6.0.0.0]
 - 9.0.0.0
 - Jellyfin Installation Method: [e.g. Docker, Linux, etc.]
 - Docker Linux 
 - Device: [e.g. Jellyfin Android App, Jellyfin Web on Firefox, etc.,]
 - iPhone 12 jellyfin app, & safari browser, & private browser tab
 - External Access Method: [eg. Tailscale, Cloudflare, Caddy, etc.] (only needed when the issue is seen on external networks
 - I use wireguard but not relevant
 - Theme being used: [e.g. Jellyfish, Zesty, etc.,
 - default dark theme.

**Logs**

Please provide server logs and browser console logs as applicable (make sure sensitive information is redacted)

Can provide logs if necessary, let me know if needed.

**Additional context**

Every other part of the plugin works as expected, is great, and worked fine before the latest update. I’m pretty sure this plugin was responsible for adding the watchlist section to the Home Screen sections plugin before, which no longer works. Both plugins are up to date.

**Comment by n00bcodr** [comment]
That is strange, I can see the watchlist in homescreensections. 

Can you please help me with some network logs, search for "JellyfinEnhanced" and reload the homepage.

[Gathering Logs for Troubleshooting Jellyfin Enhanced](https://github.com/n00bcodr/Jellyfin-Enhanced?tab=readme-ov-file#gathering-logs-for-troubleshooting-jellyfin-enhanced)

**Comment by kazango** [comment]
Haven’t had a chance to get on a computer yet, but after updating to 9.1.0.0 with the new manifest the watchlist is now appearing on the homepage again and everything seems better than ever. Awesome plugin and thanks.

**Comment by n00bcodr** [comment]
Good to hear!

Have a good one!

**Comment by DieserCoookie** [comment]
> Haven’t had a chance to get on a computer yet, but after updating to 9.1.0.0 with the new manifest the watchlist is now appearing on the homepage again and everything seems better than ever. Awesome plugin and thanks.

Could you elaborate? New manifest?

**Comment by n00bcodr** [comment]
> > Haven’t had a chance to get on a computer yet, but after updating to 9.1.0.0 with the new manifest the watchlist is now appearing on the homepage again and everything seems better than ever. Awesome plugin and thanks.
> 
> Could you elaborate? New manifest?

More details here : https://github.com/n00bcodr/Jellyfin-Enhanced?tab=readme-ov-file#-installation

**Comment by vin86** [comment]
Unfortunately for me doesn't work. I receive this error when move on tab watchlist (other options works without problems)

Uncaught (in promise) Error: Cannot find module './'
    at main.jellyfin.bundle.js?83eb46fe01daae3334d1:2:26192
